/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */
/* Set to 1 if you want to use floating-point internally for
   all sample representation */
#define WANT_FLOATING_POINT_SAMPLES 1


/* "include srfftw.h" */
#define FFTW_PREFIX 0

/* Define to 1 if you have the <audiofile.h> header file. */
#define HAVE_AUDIOFILE_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* "whether there is jack_midi support" */
/* #undef HAVE_JACKMIDI_H */

/* Define to 1 if you have the `asound' library (-lasound). */
#define HAVE_LIBASOUND 1

/* "whether or not lrdf support is enabled" */
#define HAVE_LRDF 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <srfftw.h> header file. */
#define HAVE_SRFFTW_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/soundcard.h> header file. */
#define HAVE_SYS_SOUNDCARD_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "galan"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "torbenh@users.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "galan"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "galan 0.3.0_beta9"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "galan"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.3.0_beta9"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.3.0_beta9"
/* Set to the maximum number of samples to process at once
   in between event-triggers. */
#define MAXIMUM_REALTIME_STEP 1024
