/* Generated by GOB (v2.0.12) on Fri Dec 15 22:02:28 2006
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 12

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "galan-compaction.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) GALAN_COMPACTION(x)
#define SELF_CONST(x) GALAN_COMPACTION_CONST(x)
#define IS_SELF(x) GALAN_IS_COMPACTION(x)
#define TYPE_SELF GALAN_TYPE_COMPACTION
#define SELF_CLASS(x) GALAN_COMPACTION_CLASS(x)

#define SELF_GET_CLASS(x) GALAN_COMPACTION_GET_CLASS(x)

/* self typedefs */
typedef GalanCompAction Self;
typedef GalanCompActionClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void galan_compaction_init (GalanCompAction * o) G_GNUC_UNUSED;
static void galan_compaction_class_init (GalanCompActionClass * c) G_GNUC_UNUSED;
static void ___1_galan_compaction_activate (GtkAction * self) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_KLASS,
	PROP_INIT_DATA
};

/* pointer to the class of our parent */
static GtkActionClass *parent_class = NULL;

GType
galan_compaction_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GalanCompActionClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) galan_compaction_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GalanCompAction),
			0 /* n_preallocs */,
			(GInstanceInitFunc) galan_compaction_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_ACTION, "GalanCompAction", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GalanCompAction *)g_object_new(galan_compaction_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GalanCompAction * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GalanCompAction *
GET_NEW_VARG (const char *first, ...)
{
	GalanCompAction *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GalanCompAction *)g_object_new_valist (galan_compaction_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
galan_compaction_init (GalanCompAction * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Galan:CompAction::init"
}
#undef __GOB_FUNCTION__
static void 
galan_compaction_class_init (GalanCompActionClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Galan:CompAction::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;
	GtkActionClass *gtk_action_class = (GtkActionClass *)c;

	parent_class = g_type_class_ref (GTK_TYPE_ACTION);

#line 22 "compaction.gob"
	gtk_action_class->activate = ___1_galan_compaction_activate;
#line 112 "galan-compaction.c"
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_pointer
		("klass" /* name */,
		 "klass" /* nick */,
		 "ComponentClass *" /* blurb */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (g_object_class,
		PROP_KLASS,
		param_spec);
	param_spec = g_param_spec_pointer
		("init_data" /* name */,
		 "id" /* nick */,
		 "InitData gpointer" /* blurb */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (g_object_class,
		PROP_INIT_DATA,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Galan:CompAction::set_property"
{
	GalanCompAction *self G_GNUC_UNUSED;

	self = GALAN_COMPACTION (object);

	switch (property_id) {
	case PROP_KLASS:
		{
#line 9 "compaction.gob"
self->klass = g_value_get_pointer (VAL);
#line 154 "galan-compaction.c"
		}
		break;
	case PROP_INIT_DATA:
		{
#line 15 "compaction.gob"
self->init_data = g_value_get_pointer (VAL);
#line 161 "galan-compaction.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Galan:CompAction::get_property"
{
	GalanCompAction *self G_GNUC_UNUSED;

	self = GALAN_COMPACTION (object);

	switch (property_id) {
	case PROP_KLASS:
		{
#line 9 "compaction.gob"
g_value_set_pointer (VAL, self->klass);
#line 192 "galan-compaction.c"
		}
		break;
	case PROP_INIT_DATA:
		{
#line 15 "compaction.gob"
g_value_set_pointer (VAL, self->init_data);
#line 199 "galan-compaction.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 22 "compaction.gob"
static void 
___1_galan_compaction_activate (GtkAction * self G_GNUC_UNUSED)
#line 219 "galan-compaction.c"
#define PARENT_HANDLER(___self) \
	{ if(GTK_ACTION_CLASS(parent_class)->activate) \
		(* GTK_ACTION_CLASS(parent_class)->activate)(___self); }
{
#define __GOB_FUNCTION__ "Galan:CompAction::activate"
{
#line 22 "compaction.gob"
	

		Self  *ich = self;
    	Sheet *s = gui_get_active_sheet();
    	sheet_build_new_component( s, ich->klass, ich->init_data );
	}}
#line 233 "galan-compaction.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER
